import { Events } from "../interfaces/interfaces";

export const events: Events[] = [
    {
        id: "18",
        name: "Blood Castle",
        type: "Events",
        infoItems: [
            '- El evento consiste en atravesar el puente colmado de mobs que invaden el evento, cuando lleguen al final del puente te encontraras con una puerta que deberas de romper y matar los mobs que te pida , asi podras romper la estatua que tirara el arma archangel.',
            '- No hay pérdida de experiencia cuando un jugador no consigue matar en el Blood Castle.',
            '- No hay pérdida de Zen cuando un jugador muere en el Blood Castle.',
            '- El lider que obtenga el arma archangel debera entregarlo al NPC que se encuentra en la zona segura, todos los miembros del party ganaran premio.',
            '- Apertura del Blood Castle 6 veces al dia.',
            '- Para mayor informacion, apretar la letra H ingame.',
            '- Duracion del Blood Castle  8 minutos.',
        ],
        entryTittle: "Como ingresar al Blood Castle",
        entryItems: [
            '- El Spirit of Archangel está ubicado dentro y fuera de la iglesia en Devias.',
            '- Para los primeros 15 jugadores que muestren el [Cloak Invisibility] al NPC Spirit of Archangel podran ingresar al blood castle.',
            '- El party puede ser establecido dentro y fuera del Blood Castle.',
            '- El nivel correspondiente del "Cloak Invisibility" para el blood castle en todas las razas será eliminado cuando entres al castillo.',
        ],
        urlEntryImg: "/assets/images/eventos/bloodcastle.png",
        urlMapImg: "/assets/images/maps/bloodcastle.jpg",
        imgEntryName: "Armor of Guardsman",
        rulesTitle: "Reglas del Blood Castle",
        rulesItems: [
            '- El Comando Warp puede ser usado despues de entrar al  Blood Castle.',
            '- Una vez alcanzado el limite de participantes(15), usted no podra ingresar.',
            '- El jugador que use "Town portal scroll" en el Blood Castle sera transportado a Devias.',
            '- Cuando un personaje muere en el Blood Castle sera trasportado a Devias.',
            '- El personaje que se encuentre en estado PK no podra entrar al  Blood Castle.',
            '- El jugador no puede irse más allá de la zona de segura después de entrar al Blood Castle antes de que el evento empiece.',
            '- Los Personajes que se quedan en el Blood Castle después del evento serán retornados a Devias.',
            '- Si el evento terminada antes de los (15 minutos) entonces  todos los monstruos desaparecerán y Blood Castle estará cerrado,',
            '- después de 1 minuto todos los personajes seran retornados a Devias.',
            '- Limite de entradas Blood Castle al dia son 2 veces por personaje.',
            '- Podras usar buff skills en la zona segura antes que inicie el evento.',
            '- El Trade no es admitido en Blood Castle.'
        ],
        rooms: [
            { level: 1, entryLevel: "15 ~ 80", entryLevel2: "10 ~ 60", reward: "Zen 5M / 5 GP / 1 Jewel Bless o Soul" },
            { level: 2, entryLevel: "81 ~ 130", entryLevel2: "61 ~ 110", reward: "Zen 6M / 5 GP / 1 Jewel Bless o Soul" },
            { level: 3, entryLevel: "131 ~ 180", entryLevel2: "111 ~ 160", reward: "Zen 8M / 10 GP / 1 Jewel Bless o Soul" },
            { level: 4, entryLevel: "181 ~ 230", entryLevel2: "161 ~ 210", reward: "Zen 10M / 10 GP / 1 Jewel Bless o Soul" },
            { level: 5, entryLevel: "231 ~ 280", entryLevel2: "211 ~ 260", reward: "Zen 12M / 15 GP / 2 Jewel Bless o Soul" },
            { level: 6, entryLevel: "281 ~ 330", entryLevel2: "261 ~ 310", reward: "Zen 15M / 15 GP / 2 Jewel Bless o Soul" },
            { level: 7, entryLevel: "331 ~ 400", entryLevel2: "331 ~ 400", reward: "Zen 20M / 20 GP / 2 Jewel Bless o Soul" },
            { level: 8, entryLevel: "1 ~ 400 ML", entryLevel2: "1 ~ 400 ML", reward: "Zen 50M / 30 GP / 3 Jewel Bless o Soul" },
        ]
    },
    {
        id: "19",
        name: "Chaos Castle",
        type: "Events",
        infoItems: [
            '- La cantidad total de participantes admitida en el Chaos Castle  es 100 descompuesto en lo siguiente:',
            '- Numero Maximo de Jugadores = 70',
            '- Numero Minimo de monstruos = 30',
            '- Si los grupos de jugadores son menos de 70 entonces los participantes seran remplazados automáticamente con monstruos.',
            '- El evento comenzará solamente cuando hay al menos 2 jugadores en el castillo(en el mismo alcance de nivel).',
            '- Si hay solamente 1 jugador la cuota de ingreso será devuelta y será forzado a que se retire del Chaos Castle.',
            '- Cuando el jugador entre al Chaos Castle su aparición será cambiada a un guardsmans.',
            '- Solamente la aparición será cambiada.Sus atributos como fuerza, vitalidad, energia, agilidad y comando seguiran siendo lo mismo.',
            '- Cada Raza tendrá una Sword, Staff o Crossbow dependiendo de su Raza.',
            '- Mascotas como Dinorant, Uniria, Fenrir, Caballo no serán permitidas en el Chaos Castle.',
            '- Apertura del Chaos Castle 12 veces al dia. (Horarios en H ingame)',
            '- Duracion del Evento: 10 Minutos.'
        ],
        entryTittle: "Como ingresar al Chaos Castle",
        entryItems: [
            '- El "Armor of Guardsman" es vendido en las tiendas de cada pueblo.',
            '- Jugadores que esten en estado PK no podran entrar al Chaos Castle.',
            '- Usted automaticamente serán transportado al castillo correspondiente de acuerdo asu nivel y el monto de zen será reducido.',
            '- El jugador no debera estar en party para poder ingresar.',
            '- No se puede tener equipado ningun anillo de transformacion.',
            '- Los montruos tendran un 70% de probabilidad de explotar al morir.',
            '- Para Entrar al Chaos Castle debe hacer click derecho en el "Armor of Guardsman" cuando veo el anuncio de la apertura.',
        ],
        urlEntryImg: "/assets/images/eventos/chaoscastle.png",
        urlMapImg: "/assets/images/maps/chaoscastle.jpg",
        imgEntryName: "Armor of Guardsman",
        rulesTitle: "Reglas del Chaos Castle",
        rulesItems: [
            '- Todas las razas en el Chaos Castle son consideradas como enemigos así que no es necesario cambiar ninguna funcion por PVP.',
            '- Los jugadores no pueden atacarse durante el tiempo de espera pero podran moverse.',
            '- El comando Party queda totalmente desabilitado hasta que acabe el Chaos Castle.',
            '- El personaje propio de jugador será puesto con un sombra para que asi puedan distinguirse de los otros personajes. (Tu personaje tendra una sombra más brillante)',
            '- El mapa se estrechará menos del exterior dependiendo del número de jugadores (incluyendo monstruos) en el castillo.',
            '- El personaje resucitará en Lorencia cuando gane o pierda el evento.',
        ],
        rooms: [
            { level: 1, entryLevel: "15 ~ 29", reward: "1 Chaos, 5 GP" },
            { level: 2, entryLevel: "30 ~ 99", reward: "1 Chaos, 5 GP" },
            { level: 3, entryLevel: "100 ~ 159", reward: "2 Chaos, 10 GP" },
            { level: 4, entryLevel: "160 ~ 219", reward: "2 Chaos, 10 GP" },
            { level: 5, entryLevel: "220 ~ 279", reward: "3 Chaos, 15 GP" },
            { level: 6, entryLevel: "280 ~ 400", reward: "3 Chaos, 20 GP" },
            { level: 7, entryLevel: "1 ~ 400 ML", reward: "5 Chaos, 30 GP" },
        ]
    },
]