export const guidesLinks = {

    invasiones: [
        { id: 1, text: "Golden", img: "/assets/images/invasions/golden.webp", width: "100px", path: "/guides/1", status: "active" },
        { id: 2, text: "Gorgon", img: "/assets/images/invasions/gorgon.webp", width: "120px", path: "/guides/2", status: "active" },
        { id: 3, text: "Golems", img: "/assets/images/invasions/golem-totem.webp", width: "140px", path: "/guides/3", status: "active" },
        { id: 4, text: "Summer", img: "/assets/images/invasions/fireflame.webp", width: "100px", path: "/guides/7", status: "active" },
        { id: 5, text: "Rabbits", img: "/assets/images/invasions/rabit.webp", width: "90px", path: "/guides/6", status: "active" },
        { id: 6, text: "New Year", img: "/assets/images/invasions/puch.webp", width: "140px", path: "/guides/8", status: "active" },
        { id: 7, text: "Ice Queen", img: "/assets/images/invasions/ice-queen.webp", width: "120px", path: "/guides/4", status: "active" },
        { id: 8, text: "Hydra", img: "/assets/images/invasions/hydra.webp", width: "170px", path: "/guides/5", status: "active" },
    ],
    semibosses: [
        { id: 1, text: "Red Dragon", img: "/assets/images/semiboss/red-dragon.png", width: "130px", path: "/guides/9", status: "active" },
        { id: 2, text: "Skeleton", img: "/assets/images/semiboss/skeleton.png", width: "90px", path: "/guides/10", status: "active" },
        { id: 3, text: "Zaikan", img: "/assets/images/semiboss/santa.png", width: "165px", path: "/guides/11", status: "active" },
        { id: 4, text: "White Wizard", img: "/assets/images/semiboss/white-wizard.png", width: "105px", path: "/guides/12", status: "active" },
        { id: 5, text: "Metal Balrog", img: "/assets/images/semiboss/metal.png", width: "130px", path: "/", status: "inactive" },
        { id: 6, text: "Erohim", img: "/assets/images/semiboss/herohim.png", width: "100px", path: "/", status: "inactive" },
    ],
    bosses: [
        { id: 1, text: "Selupan", img: "/assets/images/boss/selupan.webp", width: "170px", path: "/", status: "inactive" },
        { id: 2, text: "Medusa", img: "/assets/images/boss/medusa.webp", width: "140px", path: "/", status: "inactive" },
        { id: 3, text: "Kundun", img: "/assets/images/boss/kundun.webp", width: "210px", path: "/", status: "inactive" },
        { id: 4, text: "Bowser", img: "/assets/images/boss/boss1.webp", width: "130px", path: "/", status: "inactive" },
        { id: 5, text: "Malus", img: "/assets/images/boss/boss5.webp", width: "150px", path: "/", status: "inactive" },
        { id: 6, text: "Primagen ", img: "/assets/images/boss/boss6.webp", width: "100px", path: "/", status: "inactive" },
        { id: 7, text: "King Krusha", img: "/assets/images/boss/boss7.webp", width: "70px", path: "/", status: "inactive" },
        { id: 8, text: "Queen Zeal", img: "/assets/images/boss/boss4.webp", width: "100px", path: "/", status: "inactive" },
        { id: 9, text: "Viper ", img: "/assets/images/boss/boss2.webp", width: "115px", path: "/", status: "inactive" },
        { id: 10, text: "Brickster", img: "/assets/images/boss/boss3.webp", width: "150px", path: "/", status: "inactive" },
    ]
}


/*  export const guidesLinks = [
    { id: 1, type: "invasiones", text: "Golden", img: "/assets/images/invasions/golden.webp", width: "100px", path: "/guides/1", status: "active" },
    { id: 2, type: "invasiones", text: "Gorgon", img: "/assets/images/invasions/gorgon.webp", width: "120px", path: "/guides/2", status: "active" },
    { id: 3, type: "invasiones", text: "Golems", img: "/assets/images/invasions/golem-totem.webp", width: "140px", path: "/guides/3", status: "active" },
    { id: 4, type: "invasiones", text: "Summer", img: "/assets/images/invasions/fireflame.webp", width: "100px", path: "/guides/7", status: "active" },
    { id: 5, type: "invasiones", text: "Rabbits", img: "/assets/images/invasions/rabit.webp", width: "90px", path: "/guides/6", status: "active" },
    { id: 6, type: "invasiones", text: "New Year", img: "/assets/images/invasions/puch.webp", width: "140px", path: "/guides/8", status: "active" },
    { id: 7, type: "invasiones", text: "Ice Queen", img: "/assets/images/invasions/ice-queen.webp", width: "120px", path: "/guides/4", status: "active" },
    { id: 8, type: "invasiones", text: "Hydra", img: "/assets/images/invasions/hydra.webp", width: "170px", path: "/guides/5", status: "active" },
    { id: 0, type: "semibosses", text: "Red Dragon", img: "/assets/images/semiboss/red-dragon.png", width: "130px", path: "/guides/9", status: "active" },
    { id: 10, type: "semibosses", text: "Skeleton", img: "/assets/images/semiboss/skeleton.png", width: "90px", path: "/guides/10", status: "active" },
    { id: 11, type: "semibosses", text: "Zaikan", img: "/assets/images/semiboss/santa.png", width: "165px", path: "/guides/11", status: "active" },
    { id: 12, type: "semibosses", text: "White Wizard", img: "/assets/images/semiboss/white-wizard.png", width: "105px", path: "/guides/12", status: "active" },
    { id: 13, type: "semibosses", text: "Metal Balrog", img: "/assets/images/semiboss/metal.png", width: "130px", path: "/", status: "inactive" },
    { id: 14, type: "semibosses", text: "Erohim", img: "/assets/images/semiboss/herohim.png", width: "100px", path: "/", status: "inactive" },
    { id: 15, type: "bosses", text: "Selupan", img: "/assets/images/boss/selupan.webp", width: "170px", path: "/", status: "inactive" },
    { id: 16, type: "bosses", text: "Medusa", img: "/assets/images/boss/medusa.webp", width: "140px", path: "/", status: "inactive" },
    { id: 17, type: "bosses", text: "Kundun", img: "/assets/images/boss/kundun.webp", width: "210px", path: "/", status: "inactive" },
    { id: 18, type: "bosses", text: "Bowser", img: "/assets/images/boss/boss1.webp", width: "130px", path: "/", status: "inactive" },
    { id: 19, type: "bosses", text: "Malus", img: "/assets/images/boss/boss5.webp", width: "150px", path: "/", status: "inactive" },
    { id: 20, type: "bosses", text: "Primagen ", img: "/assets/images/boss/boss6.webp", width: "100px", path: "/", status: "inactive" },
    { id: 21, type: "bosses", text: "King Krusha", img: "/assets/images/boss/boss7.webp", width: "70px", path: "/", status: "inactive" },
    { id: 22, type: "bosses", text: "Queen Zeal", img: "/assets/images/boss/boss4.webp", width: "100px", path: "/", status: "inactive" },
    { id: 23, type: "bosses", text: "Viper ", img: "/assets/images/boss/boss2.webp", width: "115px", path: "/", status: "inactive" },
        { id: 24, type: "bosses", text: "Brickster", img: "/assets/images/boss/boss3.webp", width: "150px", path: "/", status: "inactive" },
        */