export const guidesLinks = {
    golden: [
        { id: 1, text: "Golden Budge Dragon", img: "/assets/images/invasions/golden.webp", width: "100px", path: "/guides/1", status: "active" },
        { id: 2, text: "Golden Goblin", img: "/assets/images/invasions/goldengoblin.webp", width: "100px", path: "/guides/9", status: "active" },
        { id: 3, text: "Golden Rabbit", img: "/assets/images/invasions/goldenrabbit.webp", width: "100px", path: "/guides/10", status: "active" },
        { id: 4, text: "Golden Solider", img: "/assets/images/invasions/goldensolider.webp", width: "100px", path: "/guides/11", status: "active" },
        { id: 5, text: "Golden Dark Knight", img: "/assets/images/invasions/goldendarkking.webp", width: "100px", path: "/guides/12", status: "active" },
        { id: 6, text: "Golden Titan", img: "/assets/images/invasions/gioldentitan.webp", width: "100px", path: "/guides/13", status: "active" },
    ],
    invasiones: [
        { id: 1, text: "Gorgon", img: "/assets/images/invasions/gorgon.webp", width: "110px", path: "/guides/2", status: "active" },
        { id: 2, text: "Golems", img: "/assets/images/invasions/golem-totem.webp", width: "140px", path: "/guides/3", status: "active" },
        { id: 3, text: "Ice Queen", img: "/assets/images/invasions/ice-queen.webp", width: "120px", path: "/guides/4", status: "active" },
        { id: 4, text: "Hydra", img: "/assets/images/invasions/hydra.webp", width: "150px", path: "/guides/5", status: "active" },
        { id: 5, text: "C.Goblin", img: "/assets/images/invasions/cursedgoblin.webp", width: "90px", path: "/guides/22", status: "active" },
        { id: 6, text: "Summer", img: "/assets/images/invasions/fireflame.webp", width: "100px", path: "/guides/7", status: "active" },
        { id: 7, text: "Rabbits", img: "/assets/images/invasions/rabit.webp", width: "90px", path: "/guides/6", status: "active" },
        { id: 8, text: "New Year", img: "/assets/images/invasions/puch.webp", width: "140px", path: "/guides/8", status: "active" },
    ],
    semibosses: [
        { id: 1, text: "Skeleton", img: "/assets/images/semiboss/skeleton.webp", width: "90px", path: "/guides/15", status: "active" },
        { id: 2, text: "White Wizard", img: "/assets/images/semiboss/white-wizard.webp", width: "105px", path: "/guides/17", status: "active" },
        { id: 3, text: "Red Dragon", img: "/assets/images/semiboss/red-dragon.webp", width: "130px", path: "/guides/14", status: "active" },
        { id: 4, text: "Zaikan", img: "/assets/images/semiboss/zaikan.webp", width: "135px", path: "/guides/16", status: "active" },
        { id: 5, text: "Metal Balrog", img: "/assets/images/semiboss/metal.webp", width: "130px", path: "/guides/21", status: "active" },
        { id: 6, text: "Erohim", img: "/assets/images/semiboss/herohim.webp", width: "100px", path: "/", status: "inactive" },
    ],
    bosses: [
        { id: 1, text: "Selupan", img: "/assets/images/boss/selupan.png", width: "170px", path: "/", status: "inactive" },
        { id: 2, text: "Medusa", img: "/assets/images/boss/medusa.png", width: "140px", path: "/", status: "inactive" },
        { id: 3, text: "Kundun", img: "/assets/images/boss/kundun.png", width: "210px", path: "/", status: "inactive" },
        { id: 4, text: "Bowser", img: "/assets/images/boss/boss1.png", width: "130px", path: "/", status: "inactive" },
        { id: 5, text: "Malus", img: "/assets/images/boss/boss5.png", width: "150px", path: "/", status: "inactive" },
        { id: 6, text: "Primagen ", img: "/assets/images/boss/boss6.png", width: "100px", path: "/", status: "inactive" },
        { id: 7, text: "King Krusha", img: "/assets/images/boss/boss7.png", width: "70px", path: "/", status: "inactive" },
        { id: 8, text: "Queen Zeal", img: "/assets/images/boss/boss4.png", width: "100px", path: "/", status: "inactive" },
        { id: 9, text: "Viper ", img: "/assets/images/boss/boss2.png", width: "115px", path: "/", status: "inactive" },
        { id: 10, text: "Brickster", img: "/assets/images/boss/boss3.png", width: "150px", path: "/", status: "inactive" },
    ],
    eventos: [
        { id: 1, text: "Blood Castle", img: "/assets/images/eventos/bloodcastle.png", width: "140px", path: "/guides/18", status: "active" },
        { id: 2, text: "Chaos Castle", img: "/assets/images/eventos/chaoscastle.png", width: "140px", path: "/guides/19", status: "active" },
        { id: 3, text: "Devil Square", img: "/assets/images/eventos/devil.png", width: "130px", path: "/guides/20", status: "active" },
        { id: 4, text: "Mirror Dimensions", img: "/assets/images/eventos/mirror.png", width: "140px", path: "/", status: "inactive" },
        { id: 5, text: "Imperial Guardian", img: "/assets/images/eventos/gaion.png", width: "140px", path: "/", status: "inactive" },
        { id: 6, text: "Rey del Mu", img: "/assets/images/eventos/reydelmu.png", width: "140px", path: "/", status: "inactive" },
        { id: 7, text: "Castle Siege", img: "/assets/images/eventos/cscs.png", width: "140px", path: "/", status: "inactive" },
    ],
    maps: [
        { id: 1, text: "Lorencia", path: "/guides/24", status: "active" },
        { id: 2, text: "Noria", path: "/guides/25", status: "active" },
        { id: 3, text: "Devias", path: "/guides/26", status: "active" },
        { id: 4, text: "Dungeon", path: "/guides/27", status: "active" },
        { id: 5, text: "Elbeland", path: "/guides/28", status: "active" },
        { id: 6, text: "Atlans", path: "/guides/29", status: "active" },
        { id: 7, text: "Tarkan", path: "/guides/30", status: "active" },
        { id: 8, text: "Aida", path: "/guides/31", status: "active" },
    ]
}